### ISSUE TITLE
Some characters are escaped twice

### ISSUE THREAD

**Issue by krummler** [commonmark/cmark#276] opened 2018-11-13 09:44 UTC
First off, thanks for this great library!

## What did you expect to happen?

I expect characters to be rendered like their unescaped counterparts, for example:
- `&amp;` becomes `&`
- `&quot;` becomes `"`
- `&lt;` becomes `<`

## What happened instead?

Most characters seem to work fine, except for `&gt;` and `&lt;` (maybe there are more cases). 
- `&amp;` stays `&amp;` which renders as `&`
- `&quot;` stays `&quot;` which renders as `"`
- `&lt;` becomes `&amp;lt;` which renders as `&lt;`
- `&gt;` becomes `&amp;gt;` which renders as `&gt;`

## Example

    &amp; Hello\n\n&quot; Hai\n\n&lt; Does that work\n\n&gt; Maybe

Becomes:

    "<p>&amp; Hello</p>\n<p>&quot; Hai</p>\n<p>&amp;lt; Does that work</p>\n<p>&amp;gt; Maybe</p>\n"

**Comment by jgm** [comment] 2018-11-13 17:41
I can't reproduce this:
```
 % ./cmark
&amp; Hello\n\n&quot; Hai\n\n&lt; Does that work\n\n&gt; Maybe
^D
<p>&amp; Hello\n\n&quot; Hai\n\n&lt; Does that work\n\n&gt; Maybe</p>
```
What version are you using?

**Comment by jgm** [comment] 2019-02-23 19:47
Closing unless more information can be provided that would allow me to reproduce this.

**Closed by jgm** 2019-02-23 19:47 UTC
