### ISSUE TITLE
[foo](<bar>"baz") interpretation

### ISSUE THREAD

**Issue by shyouhei** [commonmark/cmark#229] opened 2017-08-10 03:39 UTC
Current implementation does not understand the subject input:

```
% echo '[foo](<bar>"baz")' | cmark
<p>[foo](<bar>&quot;baz&quot;)</p>
```

However, I think `<bar>"baz"` is a valid link destination. The spec http://spec.commonmark.org/0.28/#link-destination says:

> A link destination consists of either
>
> - a sequence of zero or more characters between an opening `<` and a closing `>` that contains no spaces, line breaks, or unescaped `<` or `>` characters, or
> - a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

Isn't it clear that `<bar>"baz"` is "a nonempty sequence of characters that does not include ASCII space or control characters" ?

**Comment by mity** [comment] 2017-08-10 05:54
I believe this is duplicate of https://github.com/commonmark/cmark/issues/193#issuecomment-320490129.

**Comment by shyouhei** [comment] 2017-08-10 08:38
Yes, it seems to be.  I wasn't aware of that issue. Thank you for pointing this out.

Feel free to close this one.

**Closed** 2019-03-19 23:38 UTC
